### PR TITLE
New function : display server time

### PR DESCRIPTION
**Pull request by zeno0207**
display server time on the scoreboard
Source code referred : https://github.com/CAICCU/AccessCai/blob/main/Classes/KFScoreBoard.uc#L268

### CODE REVIEW

**Comment by GenZmeY** [comment]
Thanks for the PR

The scoreboard already has server time (bottom right corner of the panel, under the wave number). Judging by the code, you propose to add the local time of the player in the space between the number of players and the server time.

I have to reject (or at least postpone) this addition:

1. I don't know how it looks (it would be nice if you attached a screenshot), but it seems to me that the readability of the panel will suffer if there are two times next to each other without any signatures or markers

2. The current version of the scoreborad looks correct in all resolutions, nowhere does the text overlap each other. I have a concern that this may become a problem if the bottom line is filled with text more densely. This PR definitely needs to be tested in other resolutions (I don't want to do this, tbh)

If you do not agree with my arguments, you can always publish your fork, I specifically chose a license that allows other people to develop and distribute their modifications

**Review by zeno0207 — COMMENTED** [review]
encrease HeaderWidthRatio

**Comment by zeno0207** [comment]
Sorry,I am busy recently.Here are screenshots in all languages.(https://photos.app.goo.gl/vTb3cen6rycBJGMw7)
As you said,the text overlap each other in specific language such as russian.So I try to encrease the width of header from 0.3 to 0.4.(https://photos.app.goo.gl/M24VGWx3dBydHoQX8)
I also test in different resolutions.(https://photos.app.goo.gl/PAkuRxJrtMFgBwM59)

**Comment by GenZmeY** [comment]
Thanks for the screenshots, I took a look

I know you put some time and effort into this, but I like the current look of the scoreboard better than the one with the date and time on it, so I guess I'll leave it as is. I hope you're not too upset.

I think you should post your version in the workshop if you want this feature

**Pull request closed without merging**
